services:
  - type: web
    name: repo-scanner-api
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYPAL_ME
        value: bsknap
      - key: PAYPAL_EMAIL
        sync: false